### ISSUE TITLE
Potential leak in example

### ISSUE THREAD

**Issue by dbarwacz** [googlesamples/google-server-auth-android#2]
This example probably leaks activity that created login screen.
Server handler initialisation stores hard reference to activity (mServerAuthHandler = new ServerAuthHandler(this))
This handler is then used in google api client builder. 
After successful connection, the reference to mServerAuthHandler is still kept after LeakCanary's default 5s. Despite using disconnect I can't force it to release the memory.
I use fast network connection so although possible, it is very unlikely that lock would be release after some more time.

**Comment by samtstern** [comment]
Thanks for catching this, I think you are right.  I will look at this when I update the whole application to use the new Sign In API.

See https://github.com/googlesamples/google-services/blob/master/android/signin/app/src/main/java/com/google/samples/quickstart/signin/ServerAuthCodeActivity.java

**Comment by samtstern** [comment]
Now that I look at it, this whole repo should be 'deprecated' since the repo linked above has a more recent and more correct implementation.  I am going to close all issues and update the README.
